<?php
/**
 * @file
 * Contains invite functionality for the Group module.
 *
 * @todo On user register, turn invites into pending memberships.
 */

/**
 * Load our router functions without polluting the .module file.
 */
module_load_include('inc', 'ginvite', 'ginvite.router');

/**
 * Implements hook_forms().
 */
function ginvite_forms($form_id, $args) {
  $forms['ginvite_by_user_form'] = array(
    'callback' => 'ginvite_form',
  );

  $forms['ginvite_by_mail_form'] = array(
    'callback' => 'ginvite_form',
  );

  return $forms;
}

/**
 * Implements hook_init().
 *
 * Check for invites on every non-anonymous page load.
 */
function ginvite_init() {
  global $user;

  if ($user->uid) {
    if (GroupMembership::getByStatus($user->uid, GROUP_MEMBERSHIP_INVITED)) {
      $message = 'You have pending group invitations. <a href="@url">Visit your profile</a> to see them.';
      $replace = array('@url' => url("user/$user->uid/group/invite"));
      drupal_set_message(t($message, $replace), 'warning', FALSE);
    }
  }
}


/**
 * Get group invitations for a given e-mail address.
 *
 * @param string $mail
 *   The e-mail address to retrieve invites for.
 *
 * @return array
 *   An array of database records keyed by the group id.
 */
function ginvite_get_invites($mail) {
  return db_select('group_invite', 'gi')
    ->fields('gi')
    ->condition('mail', $mail)
    ->execute()
    ->fetchAllAssoc('gid');
}

/**
 * Implements hook_admin_paths().
 */
function ginvite_admin_paths() {
  if (variable_get('group_admin_theme')) {
    $paths = array(
      'group/*/invite' => TRUE,
      'group/*/invite/*' => TRUE,
    );

    return $paths;
  }
}
